baseURL = 'https://grayvox.com'
languageCode = 'en-us'
title = 'grayvox'
theme = 'risotto'

[params.theme]
palette = 'tokyo-night-dark'

[params.about]
title = 'Grayvox'
description = 'Programmer. Game Dev. Absurd Creative.'
logo = '🐺'

[menu]

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10

  [[menu.main]]
    identifier = "updates"
    name = "Updates"
    url = "/updates/"
    weight = 10

[[params.socialLinks]]
icon = 'fa-brands fa-bluesky'
title = 'Email'
url = 'https://bsky.app/profile/grayvox.com'

[[params.socialLinks]]
icon = 'fa-brands fa-itch-io'
title = 'itch.io'
url = 'https://grayvox.itch.io'

[[params.socialLinks]]
icon = 'fa-solid fa-code-branch'
title = 'Git'
url = 'https://github.com/Grayvox'


